import { Injectable } from '@angular/core';
import { Observable, of } from 'rxjs';
import { delay, map } from 'rxjs/operators';
import { HttpClient } from '@angular/common/http';

export interface Person {
    id: number;
    phoneNo: string;
    name: string;
    gender: string;
    email: string;
    nationality: string;
}

@Injectable({
    providedIn: 'root'
})
export class DataService {
    constructor(private http: HttpClient) { }

    getPeople() {
        let items = getMockPeople();
        return items;
    }
}

function getMockPeople() {
    return [
        {
            "id": 1,
            "name": "Clare Cornau",
            "phoneNo": "(815) 6180492",
            "email": "ccornau0@bigcartel.com",
            "gender": "Female",
            "nationality": "Somalia",
          },
          {
            "id": 2,
            "name": "Edouard Elsmore",
            "phoneNo": "(507) 3119958",
            "email": "eelsmore1@goo.gl",
            "gender": "Male",
            "nationality": "United States",
          },
          {
            "id": 3,
            "name": "Aeriel Elldred",
            "phoneNo": "(478) 7181722",
            "email": "aelldred2@archive.org",
            "gender": "Female",
            "nationality": "Russia",
          },
          {
            "id": 4,
            "name": "Abagael Meachem",
            "phoneNo": "(698) 4411762",
            "email": "ameachem3@columbia.edu",
            "gender": "Female",
            "nationality": "China",
          },
          {
            "id": 5,
            "name": "Jeremiah Hadwen",
            "phoneNo": "(345) 6582965",
            "email": "jhadwen4@vkontakte.ru",
            "gender": "Male",
            "nationality": "Mongolia",
          },
          {
            "id": 6,
            "name": "Rollin Wainscoat",
            "phoneNo": "(659) 9557733",
            "email": "rwainscoat5@thetimes.co.uk",
            "gender": "Male",
            "nationality": "Bhutan",
          },
          {
            "id": 7,
            "name": "Micah Braddock",
            "phoneNo": "(864) 2101861",
            "email": "mbraddock6@yellowbook.com",
            "gender": "Male",
            "nationality": "Peru",
          },
          {
            "id": 8,
            "name": "Jayme Crotty",
            "phoneNo": "(165) 5814372",
            "email": "jcrotty7@opensource.org",
            "gender": "Male",
            "nationality": "Niger",
          },
          {
            "id": 9,
            "name": "Margo Braker",
            "phoneNo": "(428) 2282928",
            "email": "mbraker8@yahoo.co.jp",
            "gender": "Female",
            "nationality": "Argentina",
          },
          {
            "id": 10,
            "name": "Bertie Bosman",
            "phoneNo": "(673) 5170425",
            "email": "bbosman9@google.co.jp",
            "gender": "Female",
            "nationality": "Greece",
          },
          {
            "id": 11,
            "name": "Darelle Rowlands",
            "phoneNo": "(978) 8885907",
            "email": "drowlandsa@slate.com",
            "gender": "Female",
            "nationality": "Indonesia",
          },
          {
            "id": 12,
            "name": "Neile Keets",
            "phoneNo": "(956) 9360112",
            "email": "nkeetsb@canalblog.com",
            "gender": "Female",
            "nationality": "Finland",
          },
          {
            "id": 13,
            "name": "Shari Bussen",
            "phoneNo": "(240) 7150720",
            "email": "sbussenc@so-net.ne.jp",
            "gender": "Female",
            "nationality": "Philippines",
          },
          {
            "id": 14,
            "name": "Arron Drivers",
            "phoneNo": "(416) 4076124",
            "email": "adriversd@com.com",
            "gender": "Male",
            "nationality": "Bosnia and Herzegovina",
          },
          {
            "id": 15,
            "name": "Carola Balasin",
            "phoneNo": "(262) 7945277",
            "email": "cbalasine@blogger.com",
            "gender": "Female",
            "nationality": "Bolivia",
          },
          {
            "id": 16,
            "name": "Clarinda Barrick",
            "phoneNo": "(501) 3984600",
            "email": "cbarrickf@t-online.de",
            "gender": "Female",
            "nationality": "China",
          },
          {
            "id": 17,
            "name": "Inglis Treweela",
            "phoneNo": "(718) 4157883",
            "email": "itreweelag@tripod.com",
            "gender": "Male",
            "nationality": "Finland",
          },
          {
            "id": 18,
            "name": "Yardley Georgeot",
            "phoneNo": "(213) 5730967",
            "email": "ygeorgeoth@360.cn",
            "gender": "Male",
            "nationality": "Portugal",
          },
          {
            "id": 19,
            "name": "Hestia Palffrey",
            "phoneNo": "(349) 6453938",
            "email": "hpalffreyi@nba.com",
            "gender": "Female",
            "nationality": "Madagascar",
          },
          {
            "id": 20,
            "name": "Gwendolyn Mordon",
            "phoneNo": "(474) 3068249",
            "email": "gmordonj@uiuc.edu",
            "gender": "Female",
            "nationality": "Greece",
          },
          {
            "id": 1,
            "name": "Clare Cornau",
            "phoneNo": "(815) 6180492",
            "email": "ccornau0@bigcartel.com",
            "gender": "Female",
            "nationality": "Somalia",
          },
          {
            "id": 2,
            "name": "Edouard Elsmore",
            "phoneNo": "(507) 3119958",
            "email": "eelsmore1@goo.gl",
            "gender": "Male",
            "nationality": "United States",
          },
          {
            "id": 3,
            "name": "Aeriel Elldred",
            "phoneNo": "(478) 7181722",
            "email": "aelldred2@archive.org",
            "gender": "Female",
            "nationality": "Russia",
          },
          {
            "id": 4,
            "name": "Abagael Meachem",
            "phoneNo": "(698) 4411762",
            "email": "ameachem3@columbia.edu",
            "gender": "Female",
            "nationality": "China",
          },
          {
            "id": 5,
            "name": "Jeremiah Hadwen",
            "phoneNo": "(345) 6582965",
            "email": "jhadwen4@vkontakte.ru",
            "gender": "Male",
            "nationality": "Mongolia",
          },
          {
            "id": 6,
            "name": "Rollin Wainscoat",
            "phoneNo": "(659) 9557733",
            "email": "rwainscoat5@thetimes.co.uk",
            "gender": "Male",
            "nationality": "Bhutan",
          },
          {
            "id": 7,
            "name": "Micah Braddock",
            "phoneNo": "(864) 2101861",
            "email": "mbraddock6@yellowbook.com",
            "gender": "Male",
            "nationality": "Peru",
          },
          {
            "id": 8,
            "name": "Jayme Crotty",
            "phoneNo": "(165) 5814372",
            "email": "jcrotty7@opensource.org",
            "gender": "Male",
            "nationality": "Niger",
          },
          {
            "id": 9,
            "name": "Margo Braker",
            "phoneNo": "(428) 2282928",
            "email": "mbraker8@yahoo.co.jp",
            "gender": "Female",
            "nationality": "Argentina",
          },
          {
            "id": 10,
            "name": "Bertie Bosman",
            "phoneNo": "(673) 5170425",
            "email": "bbosman9@google.co.jp",
            "gender": "Female",
            "nationality": "Greece",
          },
          {
            "id": 11,
            "name": "Darelle Rowlands",
            "phoneNo": "(978) 8885907",
            "email": "drowlandsa@slate.com",
            "gender": "Female",
            "nationality": "Indonesia",
          },
          {
            "id": 12,
            "name": "Neile Keets",
            "phoneNo": "(956) 9360112",
            "email": "nkeetsb@canalblog.com",
            "gender": "Female",
            "nationality": "Finland",
          },
          {
            "id": 13,
            "name": "Shari Bussen",
            "phoneNo": "(240) 7150720",
            "email": "sbussenc@so-net.ne.jp",
            "gender": "Female",
            "nationality": "Philippines",
          },
          {
            "id": 14,
            "name": "Arron Drivers",
            "phoneNo": "(416) 4076124",
            "email": "adriversd@com.com",
            "gender": "Male",
            "nationality": "Bosnia and Herzegovina",
          },
          {
            "id": 15,
            "name": "Carola Balasin",
            "phoneNo": "(262) 7945277",
            "email": "cbalasine@blogger.com",
            "gender": "Female",
            "nationality": "Bolivia",
          },
          {
            "id": 16,
            "name": "Clarinda Barrick",
            "phoneNo": "(501) 3984600",
            "email": "cbarrickf@t-online.de",
            "gender": "Female",
            "nationality": "China",
          },
          {
            "id": 17,
            "name": "Inglis Treweela",
            "phoneNo": "(718) 4157883",
            "email": "itreweelag@tripod.com",
            "gender": "Male",
            "nationality": "Finland",
          },
          {
            "id": 18,
            "name": "Yardley Georgeot",
            "phoneNo": "(213) 5730967",
            "email": "ygeorgeoth@360.cn",
            "gender": "Male",
            "nationality": "Portugal",
          },
          {
            "id": 19,
            "name": "Hestia Palffrey",
            "phoneNo": "(349) 6453938",
            "email": "hpalffreyi@nba.com",
            "gender": "Female",
            "nationality": "Madagascar",
          },
          {
            "id": 20,
            "name": "Gwendolyn Mordon",
            "phoneNo": "(474) 3068249",
            "email": "gmordonj@uiuc.edu",
            "gender": "Female",
            "nationality": "Greece",
          },
          {
            "id": 1,
            "name": "Clare Cornau",
            "phoneNo": "(815) 6180492",
            "email": "ccornau0@bigcartel.com",
            "gender": "Female",
            "nationality": "Somalia",
          },
          {
            "id": 2,
            "name": "Edouard Elsmore",
            "phoneNo": "(507) 3119958",
            "email": "eelsmore1@goo.gl",
            "gender": "Male",
            "nationality": "United States",
          },
          {
            "id": 3,
            "name": "Aeriel Elldred",
            "phoneNo": "(478) 7181722",
            "email": "aelldred2@archive.org",
            "gender": "Female",
            "nationality": "Russia",
          },
          {
            "id": 4,
            "name": "Abagael Meachem",
            "phoneNo": "(698) 4411762",
            "email": "ameachem3@columbia.edu",
            "gender": "Female",
            "nationality": "China",
          },
          {
            "id": 5,
            "name": "Jeremiah Hadwen",
            "phoneNo": "(345) 6582965",
            "email": "jhadwen4@vkontakte.ru",
            "gender": "Male",
            "nationality": "Mongolia",
          },
          {
            "id": 6,
            "name": "Rollin Wainscoat",
            "phoneNo": "(659) 9557733",
            "email": "rwainscoat5@thetimes.co.uk",
            "gender": "Male",
            "nationality": "Bhutan",
          },
          {
            "id": 7,
            "name": "Micah Braddock",
            "phoneNo": "(864) 2101861",
            "email": "mbraddock6@yellowbook.com",
            "gender": "Male",
            "nationality": "Peru",
          },
          {
            "id": 8,
            "name": "Jayme Crotty",
            "phoneNo": "(165) 5814372",
            "email": "jcrotty7@opensource.org",
            "gender": "Male",
            "nationality": "Niger",
          },
          {
            "id": 9,
            "name": "Margo Braker",
            "phoneNo": "(428) 2282928",
            "email": "mbraker8@yahoo.co.jp",
            "gender": "Female",
            "nationality": "Argentina",
          },
          {
            "id": 10,
            "name": "Bertie Bosman",
            "phoneNo": "(673) 5170425",
            "email": "bbosman9@google.co.jp",
            "gender": "Female",
            "nationality": "Greece",
          },
          {
            "id": 11,
            "name": "Darelle Rowlands",
            "phoneNo": "(978) 8885907",
            "email": "drowlandsa@slate.com",
            "gender": "Female",
            "nationality": "Indonesia",
          },
          {
            "id": 12,
            "name": "Neile Keets",
            "phoneNo": "(956) 9360112",
            "email": "nkeetsb@canalblog.com",
            "gender": "Female",
            "nationality": "Finland",
          },
          {
            "id": 13,
            "name": "Shari Bussen",
            "phoneNo": "(240) 7150720",
            "email": "sbussenc@so-net.ne.jp",
            "gender": "Female",
            "nationality": "Philippines",
          },
          {
            "id": 14,
            "name": "Arron Drivers",
            "phoneNo": "(416) 4076124",
            "email": "adriversd@com.com",
            "gender": "Male",
            "nationality": "Bosnia and Herzegovina",
          },
          {
            "id": 15,
            "name": "Carola Balasin",
            "phoneNo": "(262) 7945277",
            "email": "cbalasine@blogger.com",
            "gender": "Female",
            "nationality": "Bolivia",
          },
          {
            "id": 16,
            "name": "Clarinda Barrick",
            "phoneNo": "(501) 3984600",
            "email": "cbarrickf@t-online.de",
            "gender": "Female",
            "nationality": "China",
          },
          {
            "id": 17,
            "name": "Inglis Treweela",
            "phoneNo": "(718) 4157883",
            "email": "itreweelag@tripod.com",
            "gender": "Male",
            "nationality": "Finland",
          },
          {
            "id": 18,
            "name": "Yardley Georgeot",
            "phoneNo": "(213) 5730967",
            "email": "ygeorgeoth@360.cn",
            "gender": "Male",
            "nationality": "Portugal",
          },
          {
            "id": 19,
            "name": "Hestia Palffrey",
            "phoneNo": "(349) 6453938",
            "email": "hpalffreyi@nba.com",
            "gender": "Female",
            "nationality": "Madagascar",
          },
          {
            "id": 20,
            "name": "Gwendolyn Mordon",
            "phoneNo": "(474) 3068249",
            "email": "gmordonj@uiuc.edu",
            "gender": "Female",
            "nationality": "Greece",
          }
    ]
}
